### ISSUE TITLE
Snakdy recipe missing required config

### ISSUE THREAD

**Issue by mrjamiek** [djcass44/ci-tools#1]
Required flag "config" missing: `--config ./my-pipeline.yaml `
Surrounding quotes needed around tag stringArray: `-t="tag1,tag2,tag3"`

**Comment by djcass44** [comment]
Fixed in `v1.7.7`

**Comment by djcass44** [comment]
Additionally, config/entrypoint for the Snakdy recipes needs to be provided as an "extra arg".
For example:

```
BUILD_EXTRA_ARGS: "--entrypoint=$[[ inputs.entrypoint ]]"
```
